### ISSUE TITLE
API requests returning large JSON strings return undefined.

### ISSUE THREAD

**Issue by pixelrebel** [germanrcuriel/slack-api-client#1]
In hubot, getting a lot of undefined errors for list calls:

This works!

```
slack.api.channels.list({}, function (err, res) {
    if (err) { throw err; }
    console.log(res);
});
```

This returns "TypeError: object is not a function"

```
slack.api.users.list({}, function (err, res) {
    if (err) { throw err; }
    console.log(res);
});
```

This returns "TypeError: object is not a function"

```
slack.api.im.list({}, function (err, res) {
    if (err) { throw err; }
    console.log(res);
});
```

This returns "TypeError: Cannot read property 'list' of undefined"

```
slack.api.files.list({}, function (err, res) {
    if (err) { throw err; }
    console.log(res);
});
```

**Comment by germanrcuriel** [comment]
Hi @pixelrebel! Thanks for creating an issue. I will try to explain each case:
- `slack.api.users.list` only accepts [one argument](https://github.com/germanrcuriel/slack-api-client/blob/master/src/api/users.coffee#L23), it should be the callback function.

``` javascript
slack.api.users.list(function (err, res) {
  if (err) { throw err; }
  console.log(res);
});
```
- The [same](https://github.com/germanrcuriel/slack-api-client/blob/master/src/api/im.coffee#L23) applies to `slack api.im.list`.

``` javascript
slack.api.im.list(function (err, res) {
  if (err) { throw err; }
  console.log(res);
});
```
- And for the `slack.api.files.list` I'm afraid that the `files` resource it's not implemented yet.

Hope it helps! :wink:

**Comment by pixelrebel** [comment]
Got it working now.  Thanks!  BTW, are you working on a files.upload multipart/form-data method?  I can only get this to work via curl.  Haven't figured out how to implement using scoped-http-client.

**Comment by germanrcuriel** [comment]
Yes, I'm working on it but I don't know when I will do the release.

**Comment by pixelrebel** [comment]
Awesome, great work!
